# Generated by Django 5.1.5 on 2025-02-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FusionDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Domain Name', max_length=255)),
                ('functional_type', models.CharField(db_column='Functional Type', max_length=255)),
                ('source_protein', models.CharField(blank=True, db_column='Source Protein', max_length=255, null=True)),
                ('strain', models.CharField(blank=True, db_column='Strain', max_length=255, null=True)),
                ('length', models.FloatField(blank=True, db_column='Length', null=True)),
                ('doi', models.URLField(blank=True, db_column='DOI', null=True)),
                ('functional_role', models.TextField(blank=True, db_column='Functional Role', null=True)),
                ('applications', models.TextField(blank=True, db_column='Applications', null=True)),
                ('uniprot', models.CharField(blank=True, db_column='Uniprot', max_length=50, null=True)),
                ('sequence_aa', models.TextField(blank=True, db_column='Sequence (Amino Acid)', null=True)),
                ('sequence_nt', models.TextField(blank=True, db_column='Sequence (Nucleotide)', null=True)),
            ],
            options={
                'db_table': 'Fusion_Domains',
            },
        ),
        migrations.CreateModel(
            name='ModifiedPolymerase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Polymerase_Name', max_length=255)),
                ('base_polymerase', models.CharField(db_column='Base_Polymerase', max_length=255)),
                ('modification_type', models.CharField(db_column='Modification_Type', max_length=255)),
                ('modifications', models.TextField(blank=True, db_column='Modifications', null=True)),
                ('optimal_temp', models.FloatField(blank=True, db_column='Optimal_Temperature_c', null=True)),
                ('melting_temp', models.FloatField(blank=True, db_column='Melting_Temperature_c', null=True)),
                ('processivity', models.FloatField(blank=True, db_column='Processivity_bp', null=True)),
                ('binding_affinity', models.FloatField(blank=True, db_column='Binding_Affinity_kd', null=True)),
                ('ph_range', models.CharField(blank=True, db_column='pH_Stability_Range', max_length=50, null=True)),
                ('optimal_ph', models.FloatField(blank=True, db_column='Optimal_pH', null=True)),
                ('salt_tolerance_nacl', models.FloatField(blank=True, db_column='Salt_Tolerance_mM_NaCl', null=True)),
                ('salt_tolerance_kcl', models.FloatField(blank=True, db_column='Salt_Tolerance_mM_KCI', null=True)),
                ('activity', models.FloatField(blank=True, db_column='Activity', null=True)),
                ('exo_activity', models.CharField(blank=True, db_column='exo_activity_5_3', max_length=50, null=True)),
                ('enhanced_properties', models.TextField(blank=True, db_column='Enhanced_Properties', null=True)),
                ('applications', models.TextField(blank=True, db_column='Applications', null=True)),
                ('doi', models.URLField(blank=True, db_column='DOI', null=True)),
            ],
            options={
                'db_table': 'Modified_Polymerases',
            },
        ),
        migrations.CreateModel(
            name='WildTypePolymerase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Polymerase_Name', max_length=255)),
                ('source_strain', models.CharField(db_column='Source strain', max_length=255)),
                ('family', models.CharField(db_column='Family', max_length=50)),
                ('exo_activity', models.CharField(db_column='exo_activity_5_3', max_length=50)),
                ('doi', models.URLField(db_column='DOI')),
            ],
            options={
                'db_table': 'Wild_type_Polymerases',
            },
        ),
    ]
