# Generated by Django 5.1.5 on 2025-02-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polymes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildtypepolymerase',
            name='doi',
            field=models.TextField(db_column='DOI', null=True),
        ),
        migrations.AlterField(
            model_name='wildtypepolymerase',
            name='exo_activity',
            field=models.TextField(db_column='exo_activity_5_3', null=True),
        ),
        migrations.AlterField(
            model_name='wildtypepolymerase',
            name='family',
            field=models.TextField(db_column='Family', null=True),
        ),
        migrations.AlterField(
            model_name='wildtypepolymerase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wildtypepolymerase',
            name='name',
            field=models.TextField(db_column='Polymerase_Name'),
        ),
        migrations.AlterField(
            model_name='wildtypepolymerase',
            name='source_strain',
            field=models.TextField(db_column='Source strain', null=True),
        ),
    ]
