# Generated by Django 5.1.5 on 2025-02-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polymes', '0003_remove_fusiondomain_applications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedpolymerase',
            name='binding_affinity',
            field=models.IntegerField(db_column='Binding_Affinity_kd', null=True),
        ),
        migrations.AddField(
            model_name='modifiedpolymerase',
            name='enhanced_properties',
            field=models.TextField(db_column='Enhanced_Properties', null=True),
        ),
        migrations.AddField(
            model_name='modifiedpolymerase',
            name='exo_activity_5_3',
            field=models.TextField(db_column='exo_activity_5_3', null=True),
        ),
        migrations.AddField(
            model_name='modifiedpolymerase',
            name='melting_temp',
            field=models.IntegerField(db_column='Melting_Temperature_c', null=True),
        ),
        migrations.AddField(
            model_name='modifiedpolymerase',
            name='modifications',
            field=models.TextField(db_column='Modifications', null=True),
        ),
        migrations.AddField(
            model_name='modifiedpolymerase',
            name='optimal_ph',
            field=models.IntegerField(db_column='Optimal_pH', null=True),
        ),
        migrations.AddField(
            model_name='modifiedpolymerase',
            name='ph_stability',
            field=models.TextField(db_column='pH_Stability_Range', null=True),
        ),
        migrations.AddField(
            model_name='modifiedpolymerase',
            name='processivity',
            field=models.IntegerField(db_column='Processivity_bp', null=True),
        ),
        migrations.AddField(
            model_name='modifiedpolymerase',
            name='salt_tolerance_kcl',
            field=models.IntegerField(db_column='Salt_Tolerance_mM_KCl', null=True),
        ),
        migrations.AddField(
            model_name='modifiedpolymerase',
            name='salt_tolerance_nacl',
            field=models.IntegerField(db_column='Salt_Tolerance_mM_NaCl', null=True),
        ),
    ]
