# Generated by Django 5.1.5 on 2025-02-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polymes', '0004_modifiedpolymerase_binding_affinity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiedpolymerase',
            name='salt_tolerance_kcl',
            field=models.IntegerField(db_column='Salt_Tolerance_mM_KCI', null=True),
        ),
    ]
